server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: relational-database-service
          uri: http://relational-database-service
          predicates:
            - Path=/relational-database-service/**
            
        - id: timeseries-database-service
          uri: http://timeseries-database-service
          predicates:
            - Path=/timeseries-database-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"  # Update with your frontend URL
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
